from __future__ import annotations

import argparse
import csv
import json
import os
from dataclasses import asdict
from pathlib import Path

from .alpha_vantage import AlphaVantageTranscriptSource
from .transcript_collection import TranscriptRequest, collect_requested_transcripts
from .transcript_store import FileTranscriptStore

DEFAULT_REQUEST_FILES = (
    Path("experiments/validation_semiconductor_2021_requests.csv"),
    Path("experiments/validation_auto_2021_requests.csv"),
    Path("experiments/validation_semiconductor_2019q2_control_requests.csv"),
    Path("experiments/validation_semiconductor_2019q3_control_requests.csv"),
    Path("experiments/validation_auto_2019q2_control_requests.csv"),
    Path("experiments/pilot_power_infrastructure_requests.csv"),
)
DEFAULT_BLIND_REQUEST_FILE = Path("var/cohort/neutral_proxy_requests.csv")


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Collect every frozen Phase-1 validation transcript request cache-first under one "
            "global provider budget, including the retained power pilot. Re-run safely on later days "
            "to resume from cache."
        )
    )
    parser.add_argument("--transcript-root", type=Path, default=Path("var/transcripts"))
    parser.add_argument("--max-provider-requests", type=int, default=24)
    parser.add_argument("--interval-seconds", type=float, default=1.1)
    parser.add_argument(
        "--blind-requests",
        type=Path,
        default=DEFAULT_BLIND_REQUEST_FILE,
        help="Generated by ibs-phase1-proxy-plan; omitted automatically when not present",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("var/validation/collection-status.json"),
    )
    return parser


def _load_requests(path: Path) -> tuple[TranscriptRequest, ...]:
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if not {"ticker", "quarter"}.issubset(set(reader.fieldnames or ())):
            raise ValueError(f"{path}: request CSV requires ticker and quarter columns")
        return tuple(
            TranscriptRequest(
                ticker=(row.get("ticker") or ""),
                quarter=(row.get("quarter") or ""),
            )
            for row in reader
        )


def _dedupe(requests: list[TranscriptRequest]) -> tuple[TranscriptRequest, ...]:
    seen: set[tuple[str, str]] = set()
    unique: list[TranscriptRequest] = []
    for request in requests:
        key = (request.ticker, request.quarter)
        if key in seen:
            continue
        seen.add(key)
        unique.append(request)
    return tuple(unique)


def _is_available(
    store: FileTranscriptStore,
    *,
    provider: str,
    request: TranscriptRequest,
) -> bool:
    return store.load(provider=provider, ticker=request.ticker, quarter=request.quarter) is not None


def _coverage_for_file(
    path: Path,
    *,
    store: FileTranscriptStore,
    provider: str,
) -> dict[str, object]:
    requests = _dedupe(list(_load_requests(path)))
    available = [
        request
        for request in requests
        if _is_available(store, provider=provider, request=request)
    ]
    missing = [
        request
        for request in requests
        if not _is_available(store, provider=provider, request=request)
    ]
    return {
        "planned": len(requests),
        "available": len(available),
        "remaining": len(missing),
        "complete": not missing,
        "missing_requests": [asdict(item) for item in missing],
    }


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.max_provider_requests < 1:
        raise SystemExit("--max-provider-requests must be at least 1")
    if args.interval_seconds < 0:
        raise SystemExit("--interval-seconds must be non-negative")

    api_key = os.environ.get("ALPHA_VANTAGE_API_KEY", "").strip()
    if not api_key:
        raise SystemExit("ALPHA_VANTAGE_API_KEY environment variable is required")

    request_files = list(DEFAULT_REQUEST_FILES)
    if args.blind_requests.exists():
        request_files.append(args.blind_requests)

    requests: list[TranscriptRequest] = []
    for path in request_files:
        if not path.exists():
            raise SystemExit(f"required validation request file not found: {path}")
        requests.extend(_load_requests(path))
    planned = _dedupe(requests)

    store = FileTranscriptStore(args.transcript_root)
    source = AlphaVantageTranscriptSource(api_key=api_key)
    summary = collect_requested_transcripts(
        source,
        store=store,
        requests=planned,
        max_provider_requests=args.max_provider_requests,
        min_interval_seconds=args.interval_seconds,
    )

    available_requests = [
        item
        for item in planned
        if _is_available(store, provider=source.provider_name, request=item)
    ]
    missing_requests = [
        item
        for item in planned
        if not _is_available(store, provider=source.provider_name, request=item)
    ]
    request_file_coverage = {
        str(path): _coverage_for_file(
            path,
            store=store,
            provider=source.provider_name,
        )
        for path in request_files
    }

    payload = {
        "provider": source.provider_name,
        "request_files": [str(path) for path in request_files],
        "blind_requests_included": args.blind_requests in request_files,
        "power_pilot_requests_included": Path("experiments/pilot_power_infrastructure_requests.csv") in request_files,
        "planned_unique_requests": len(planned),
        "available_after_run": len(available_requests),
        "remaining_after_run": len(missing_requests),
        "missing_requests": [asdict(item) for item in missing_requests],
        "request_file_coverage": request_file_coverage,
        "run": asdict(summary),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    status = "complete" if not missing_requests else ("rate_limited" if summary.rate_limited else "incomplete")
    complete_files = sum(bool(item["complete"]) for item in request_file_coverage.values())
    print(
        f"status={status} planned={len(planned)} available={len(available_requests)} "
        f"remaining={len(missing_requests)} complete_request_files={complete_files}/{len(request_file_coverage)} "
        f"cache_hits={summary.cache_hits} fetched={summary.fetched} "
        f"provider_requests={summary.provider_requests} rate_limited={summary.rate_limited} errors={summary.errors}"
    )
    print(f"wrote {args.output}")
    return 0 if not missing_requests else 2


if __name__ == "__main__":
    raise SystemExit(main())
