from __future__ import annotations

FROZEN_VALIDATION_POLICY_ID = "phase1-validation-v1"
FROZEN_V1_MIN_POSITIVE_RECALL = 0.67
FROZEN_V1_MIN_EXPECTED_METRIC_RECALL = 0.67
FROZEN_V1_MAX_CONTROL_FALSE_POSITIVE_RATE = 0.20
FROZEN_V1_REQUIRE_AGGREGATION_MATCH = True
